AWSTemplateFormatVersion: 2010-09-09
Description: Simple calculator app
Transform: AWS::Serverless-2016-10-31
Resources:
  calcApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: "./api/calcApiDefinition.json"
      Name: calcAppApi
      OpenApiVersion: 3.0.1
      StageName: v1
      TracingEnabled: true
  calcFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/calc.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function which performs some calculations
      Events:
        calcApiGETEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref calcApi
        calcApiPOSTEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref calcApi
        calcApiPathEvent:
          Type: Api
          Properties:
            Path: /{a}/{b}/{op}
            Method: get
            RestApiId: !Ref calcApi